---

- name: Add Kubernetes CentOS7 yum repo
  yum_repository:
    name: kubernetes
    description: Kubernetes Yum Repo
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    gpgcheck: no
    state: present

- name: Add Kubernetes CentOS7 yum repo
  yum_repository:
    name: kubernetes
    description: Kubernetes Yum Repo
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    gpgcheck: no
    state: present

- name: Install Kubernetes basics
  yum: name="{{item}}" state=installed
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni
    - ebtables
    - ethtool

- name: Pull K8s Docker images
  docker_image:
    name: "{{item}}"
  with_items:
    - "gcr.io/google_containers/kube-apiserver-amd64:v1.8.2"
    - "gcr.io/google_containers/kube-controller-manager-amd64:v1.8.2"
    - "gcr.io/google_containers/kube-scheduler-amd64:v1.8.2"

- name: Ensure kubelet is started and enabled at boot.
  service:
    name: kubelet
    state: started
    enabled: yes

...
