---

# TODO: Not sure this should be here
- name: Disable SELinux
  selinux:
    state: disabled

# TODO: Need to run the following here
# iptables -t nat -F
# ip link set docker0 down
# ip link delete docker0

- name: Ensure Kernel setting for net.bridge.bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes

- import_tasks: centos-kubernetes.yml

- name: Disable firewalld
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  with_items:
    - firewalld

# TODO: Not sure this should be here
- name: Disable firewalld
  systemd:
    name: "{{item}}"
    enabled: no
    state: stopped
  with_items:
    - firewalld

- name: Enable systemd components for Kubernetes
  systemd:
    name: "{{item}}"
    enabled: yes
    state: started
  with_items:
    - docker
    - kubelet

...
