######################################################
################ Configure Runlevel ##################
######################################################
---
- hosts: all
  tasks:
    - name: 'Set up services var'
      set_fact:
        services: []
        services: "{{ services }} + [ 'bro' ]"
        when: with_bro
        services: "{{ services }} + [ 'snort' ]"
        when: with_snort
        services: "{{ services }} + [ 'kafka' ]"
        when: with_kafka
        services: "{{ services }} + [ 'lighttpd' ]"
        when: with_lighttpd
        services: "{{ services }} + [ 'harbor' ]"
        when: with_harbor
        services: "{{ services }} + [ 'docker' ]"
        when: with_docker
        services: "{{ services }} + [ 'docket' ]"
        when: with_docket
        services: "{{ services }} + [ 'elasticsearch' ]"
        when: with_elasticsearch
        services: "{{ services }} + [ 'zookeeper' ]"
        when: with_zookeeper
        services: "{{ services }} + [ 'logstash' ]"
        when: with_logstash
        services: "{{ services }} + [ 'portainer' ]"
        when: with_portainer
        services: "{{ services }} + [ 'kibana' ]"
        when: with_kibana
        services: "{{ services }} + [ 'suricata' ]"
        when: with_suricata
        services: "{{ services }} + [ 'stenographer' ]"
        when: with_stenographer
        services: "{{ services }} + [ 'fsf' ]"
        when: with_fsf
    - debug:
        var: services

  - name: 'Render rock_start template'
    template:
      backup: yes
      src: rock.target.j2
      dest: /etc/systemd/system/rock.target
      owner: root
      group: root
      mode: 0644

  - name: 'Create rock.target.wants'
    file:
      path: /etc/systemd/system/rock.target.wants
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: 'Add systemd rock.target wants'
    file:
      src: "{{ lookup('first_found', dict(files=['/etc/systemd/system/' + item + '.service', '/usr/lib/systemd/system/' + item + '.service'], skip=true)) }}"
      dest: /etc/systemd/system/rock.target.wants/{{ item }}.service
      state: link
    dothing: "'with_' + {{ item }}"
    when: dothing
    with_items: "{{ services }}"
    ignore_errors: yes

  - name: 'Check default runlevel'
    command: systemctl get-default
    register: runlevel

  - name: 'Change default runlevel'
    command: systemctl set-default rock.target
    when: runlevel.stdout != "rock.target"

  - name: 'Check current runlevel'
    command: systemctl is-active rock.target
    register: runlevel_active
    failed_when: runlevel_active.rc != 3
    ignore_errors: yes

  - name: 'Switch to rock.target'
    command: systemctl isolate rock.target
    when: runlevel_active.stdout != "active"
