######################################################
################ Configure Runlevel ##################
######################################################
---
- hosts: all
  vars:
    services:
    - bro
    - snort
    - kafka
    - lighttpd
    - harbor
    - docker
    - docket
    - elasticsearch
    - zookeeper
    - logstash
    - portainer
    - kibana
    - suricata
    - stenographer
    - fsf

  tasks:
  - name: 'Render rock_start template'
    template:
      backup: yes
      src: rock.target.j2
      dest: /etc/systemd/system/rock.target
      owner: root
      group: root
      mode: 0644

  - name: 'Create rock.target.wants'
    file:
      path: /etc/systemd/system/rock.target.wants
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: 'Checking for services'
    find:
      paths: /usr/lib/systemd/system/{{ item }}.service /etc/systemd/system/{{ item }}.service
    register: stat_result
    with_items: "{{ services }}"
  - debug:
      var: stat_result

  - name: 'Add systemd target wants'
    file:
      src: "{{ item.1 }}"
      dest: /etc/systemd/system/rock.target.wants/{{ item.0 }}.service
      state: link
    when: with_"{{ item.0 }}" and stat_result.stat.exists
    with_together:
      - "{{ services }}"
      - "{{ stat_result.path }}"

  - name: 'Check default runlevel'
    command: systemctl get-default
    register: runlevel

  - name: 'Change default runlevel'
    command: systemctl set-default rock.target
    when: runlevel.stdout != "rock.target"

  - name: 'Check current runlevel'
    command: systemctl is-active rock.target
    register: runlevel_active
    failed_when: runlevel_active.rc != 3
    ignore_errors: yes

  - name: 'Switch to rock.target'
    command: systemctl isolate rock.target
    when: runlevel_active.stdout != "active"
