######################################################
################# Setup Elasticsearch ################
######################################################
---

- name: "Create Elasticsearch directory"
  file:
    group: "{{ es_group }}"
    mode: u+rw,g+rw
    owner: "{{ es_user }}"
    path: "{{ es_config_dir }}"
    state: directory

- name: Install Elasticsearch templates
  template:
    src: "templates/{{ item }}.yml.j2"
    dest: "{{ es_config_dir }}/{{ item }}.yml"
    group: "root"
    owner: "root"
    mode: 0644
  with_items:
    - es-client
    - es-curator-config
    - es-curator_v1beta1
    - es-data-pdb
    - es-data
    - es-discovery-svc
    - es-master-pdb
    - es-master
    - es-svc

- name: Create Elasticsearch - Service - Discovery
  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" create -f {{ es_config_dir }}/es-discovery-svc.yml'

- name: Create Elasticsearch - Service - Elasticsearch
  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" create -f {{ es_config_dir }}/es-svc.yml'

- name: Create Elasticsearch - Master
  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" create -f {{ es_config_dir }}/es-master.yml'

- name: Rollout Elasticsearch - Master
  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" rollout status -f {{ es_config_dir }}/es-master.yml'

#- name: Create Elasticsearch - Client
#  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" create -f {{ es_config_dir }}/es-client.yml'
#
#- name: Rollout Elasticsearch - Client
#  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" rollout status -f {{ es_config_dir }}/es-client.yml'
#
#- name: Create Elasticsearch - Data
#  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" create -f {{ es_config_dir }}/es-data.yml'
#
#- name: Rollout Elasticsearch - Data
#  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" rollout status -f {{ es_config_dir }}/es-data.yml'
